name: top_dash
description: Google I/Os Top Dash game
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.2

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  firebase_storage: ^11.0.11
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  language_model_repository:
    path: packages/language_model_repository

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
